const $=id=>document.getElementById(id),F=['serial','dot','depthL','depthC','depthR','pmr','shoulder','notes'];let rows=JSON.parse(localStorage.getItem('tireV4')||'[]'),worker;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');const toast=m=>{const e=$('toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',2200)};
const L=c=>({'0':'O','1':'I','2':'Z','5':'S','8':'B'}[c]||c).replace(/[^A-Z]/g,''),D=c=>({O:'0',Q:'0',D:'0',I:'1',L:'1',Z:'2',S:'5',B:'8',G:'6'}[c]||c).replace(/[^0-9]/g,'');
function getSerial(raw){const x=(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,''),a=[];for(let i=0;i<=x.length-9;i++){const w=x.slice(i,i+9),v=[L(w[0]),L(w[1]),L(w[2]),...w.slice(3,8).split('').map(D),L(w[8])];if(v.every(Boolean)&&v[8]==='R'){const s=v.join('');a.push({s,n:(/[LFZX]/.test(s[1])?5:0)+(w[8]==='R'?3:0)})}}return a.sort((a,b)=>b.n-a.n)[0]?.s||''}function getDot(raw){const x=[...(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,'')].map(D).join('');for(let i=0;i<=x.length-4;i++){const v=x.slice(i,i+4),w=+v.slice(0,2);if(w>=1&&w<=53)return v}return ''}
function prep(file,type){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),s=Math.min(1,1500/Math.max(im.width,im.height));c.width=im.width*s;c.height=im.height*s;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0,c.width,c.height);const z=g.getImageData(0,0,c.width,c.height),a=z.data;let t=0;for(let i=0;i<a.length;i+=4){let y=.299*a[i]+.587*a[i+1]+.114*a[i+2];t+=y;a[i]=a[i+1]=a[i+2]=y}const m=t/(a.length/4);for(let i=0;i<a.length;i+=4){let y=(a[i]-m)*1.7+m;if(type!=='mark')y=y>m*.92?255:0;a[i]=a[i+1]=a[i+2]=Math.max(0,Math.min(255,y))}g.putImageData(z,0,0);c.toBlob(res,'image/png')};im.onerror=rej;im.src=URL.createObjectURL(file)})}
async function getWorker(type){if(worker)return worker;if(!window.Tesseract)throw Error('请先执行精简OCR准备脚本');worker=await Tesseract.createWorker('eng',1,{workerPath:'./vendor/tesseract/worker.min.js',corePath:window.OCR_CORE_PATH,langPath:'./vendor/tesseract/lang-data',gzip:true,logger:m=>{if(m.status==='recognizing text')$(type+'Ocr').textContent=`本机识别 ${Math.round((m.progress||0)*100)}%`}});return worker}
async function scan(file,type){$(type+'Ocr').textContent='正在增强图像';try{const w=await getWorker(type),img=await prep(file,type);await w.setParameters({tessedit_char_whitelist:type==='dot'?'0123456789':type==='serial'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789':'',tessedit_pageseg_mode:type==='mark'?'6':'7'});const {data}=await w.recognize(img),v=type==='serial'?getSerial(data.text):type==='dot'?getDot(data.text):data.text.trim();$(type+'Ocr').textContent=v?`识别：${v}，置信度${Math.round(data.confidence||0)}%，请确认`:'未找到有效格式';return v}catch(e){$(type+'Ocr').textContent=e.message;return ''}}
async function photo(e,type,target){const f=e.target.files[0];if(!f)return;const p=$(type+'Preview');p.src=URL.createObjectURL(f);p.style.display='block';const v=await scan(f,type);if(v)$(target).value=v}document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>$(b.dataset.file).click());$('serialPhoto').onchange=e=>photo(e,'serial','serial');$('dotPhoto').onchange=e=>photo(e,'dot','dot');$('markPhoto').onchange=e=>photo(e,'mark','notes');
function reset(){F.forEach(x=>$(x).value='');['serialPreview','dotPreview','markPreview'].forEach(x=>$(x).style.display='none');['serialOcr','dotOcr','markOcr'].forEach(x=>$(x).textContent='')}$('resetBtn').onclick=reset;$('saveBtn').onclick=()=>{const serial=$('serial').value.toUpperCase().replace(/[^A-Z0-9]/g,''),dot=$('dot').value.replace(/\D/g,''),week=+dot.slice(0,2);if(!/^[A-Z]{3}\d{5}R$/.test(serial))return toast('胎号格式错误，例如LLD95510R');if(!/^\d{4}$/.test(dot)||week<1||week>53)return toast('周期应为4位，周号01至53');rows.unshift({id:Date.now(),time:new Date().toLocaleString('zh-CN'),serial,dot,week,year:'20'+dot.slice(2),depthL:$('depthL').value,depthC:$('depthC').value,depthR:$('depthR').value,pmr:$('pmr').value,shoulder:$('shoulder').value,notes:$('notes').value});save();reset();toast('已保存')};
const esc=v=>String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));function save(){localStorage.setItem('tireV4',JSON.stringify(rows));render()}function render(){$('count').textContent=rows.length+'条';$('records').innerHTML=rows.length?rows.map(r=>`<div class="record"><button onclick="del(${r.id})">删除</button><b>${esc(r.serial)}</b> · ${esc(r.dot)}（${esc(r.year)}年第${esc(r.week)}周）<p>${esc(r.time)} | L/C/R ${esc(r.depthL||'-')}/${esc(r.depthC||'-')}/${esc(r.depthR||'-')} mm | PMR ${esc(r.pmr||'-')} | 肩磨 ${esc(r.shoulder||'-')}</p><p>${esc(r.notes||'无备注')}</p></div>`).join(''):'暂无记录'}window.del=id=>{rows=rows.filter(r=>r.id!==id);save()};$('clearAllBtn').onclick=()=>{if(confirm('删除全部记录？')){rows=[];save()}};
function csv(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}$('exportBtn').onclick=()=>{if(!rows.length)return toast('暂无记录');const H=['检查时间','胎号','生产周期','周号','年份','左深度','中深度','右深度','PMR代码','肩部磨损','备注'],data=[H,...rows.map(r=>[r.time,r.serial,r.dot,r.week,r.year,r.depthL,r.depthC,r.depthR,r.pmr,r.shoulder,r.notes])].map(r=>r.map(csv).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));a.download='轮胎检查_'+new Date().toISOString().slice(0,10)+'.csv';a.click()};render();
